layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    - Healthcare Claims Adjudication using Machine Learning
    - Statical Estimation of Data Quality
    - Unsupervised and Semi-Supervised Anamoly Detection
    - Document Layout Analysis
    - Information Extraction
    - Information Retrieval


social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: rajat-gupta-72137516
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: rajaty6
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:

  - name: Natural Language Processing using Deep Learning and Conventional Methods

  - name: Computer Vision Applications
  
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning

  - name: PySpark
    web_url: https://github.com/topics/pyspark
    
  - name: Microservices Development 

  - name: Python Full Stack Development 

  - name: FastApi and Flask App Development

  - name: Full Stack and Data Engineering and ML models deployment on Kubenetes / Openshift

  - name: Custom d3.js visualization

  - name: Customization of Open source libraries - Superset, Optimus